options:
  lcm-ssh-key:
    default: 'null'
    type: string
    description: Public SSH key of PLUMgrid LCM which is running PG-Tools
  mgmt-interface:
    type: string
    default: 'juju-br0'
    description: The interface connected to PLUMgrid Managment network.
  network-device-mtu:
    type: string
    default: '1580'
    description: The MTU size for interfaces managed by director.
  install_sources:
    default: 'ppa:plumgrid-team/stable'
    type: string
    description: Provide the install source from where to install the PLUMgrid debs
  install_keys:
    default: null
    type: string
    description: Provide the respective keys of the install sources
  metadata-shared-key:
    default: 'plumgrid'
    type: string
    description: Provide a key to be used as the metadata shared key
